# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_detail_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotKiller',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=16)),
                ('visits', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'robotkiller',
            },
        ),
    ]
